[build]
builder = "nixpacks"
buildCommand = "cd job-manager-ui && npm ci --only=production --silent && npm run build && cd .. && pip install --no-cache-dir -r requirements-fastapi.txt"

[deploy]
startCommand = "python fastapi_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PYTHONPATH = "/app"
PORT = "8000"
CHROME_BIN = "/usr/bin/chromium"
CHROMEDRIVER_PATH = "/usr/bin/chromedriver"