[build]
builder = "nixpacks"
buildCommand = "cd job-manager-ui && npm install && npm run build && cd .. && pip install -r requirements-fastapi.txt"

[deploy]
startCommand = "python fastapi_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PYTHONPATH = "/app"
PORT = "8000"