-- Migration: make job signatures per-user
--
-- job_signatures was UNIQUE(company, normalized_title, country) — one global row
-- per posting — while the suppression lookup in /api/jobs joined through it:
--
--     JOIN user_job_interactions uji ON uji.job_id = js.original_job_id
--     WHERE uji.user_id = $1
--
-- add_job_signature upserts with ON CONFLICT DO UPDATE SET original_job_id =
-- EXCLUDED.original_job_id, so the most recent person to reject a posting
-- overwrites that pointer. Everyone who rejected it earlier then fails the join
-- and starts seeing the job again — silently, and more often the more users
-- there are.
--
-- Making the row per-user removes the shared pointer entirely: the lookup can
-- filter on user_id directly instead of joining through original_job_id.

ALTER TABLE job_signatures ADD COLUMN IF NOT EXISTS user_id INTEGER
    REFERENCES users(id) ON DELETE CASCADE;

-- Recover ownership for signatures whose pointer still happens to be intact.
-- Rows whose pointer was already overwritten cannot be attributed here and stay
-- NULL; backfill_rejected_signatures.py can rebuild those from the interaction
-- history, which is the authoritative record.
UPDATE job_signatures js
SET user_id = uji.user_id
FROM user_job_interactions uji
WHERE js.user_id IS NULL
  AND uji.job_id = js.original_job_id
  AND (uji.applied = TRUE OR uji.rejected = TRUE);

-- The old global constraint is what forced the overwrite, and it must actually
-- go: if it survives, the second user's row for the same posting fails with a
-- unique violation instead of being stored.
--
-- Dropping it by its expected autogenerated name would silently no-op if
-- Postgres named it anything else, so find it by the columns it covers.
DO $$
DECLARE
    conname_found TEXT;
BEGIN
    SELECT c.conname INTO conname_found
    FROM pg_constraint c
    WHERE c.conrelid = 'job_signatures'::regclass
      AND c.contype = 'u'
      AND (
            SELECT array_agg(a.attname ORDER BY a.attname)
            FROM unnest(c.conkey) AS k(attnum)
            JOIN pg_attribute a
              ON a.attrelid = c.conrelid AND a.attnum = k.attnum
          ) = ARRAY['company', 'country', 'normalized_title']
    LIMIT 1;

    IF conname_found IS NOT NULL THEN
        EXECUTE format('ALTER TABLE job_signatures DROP CONSTRAINT %I', conname_found);
        RAISE NOTICE 'Dropped global unique constraint %', conname_found;
    ELSE
        RAISE NOTICE 'No global unique constraint on (company, country, normalized_title) — already migrated';
    END IF;
END $$;

-- Same uniqueness, scoped per user. Partial, so legacy rows left with a NULL
-- user_id do not collide with each other (NULLs are distinct in a UNIQUE index
-- anyway, but being explicit keeps the intent clear).
CREATE UNIQUE INDEX IF NOT EXISTS idx_job_signatures_user_unique
    ON job_signatures(user_id, company, normalized_title, country)
    WHERE user_id IS NOT NULL;

-- Whether it was an application or a rejection now lives on the signature row.
-- Previously it was derived by joining back to user_job_interactions through
-- original_job_id — but enforce-country-limit deletes old job rows, and a
-- signature whose job is gone then resolves to "neither applied nor rejected",
-- so the repost reappears. Surviving job deletion is the whole reason this table
-- exists, so the flags belong here.
ALTER TABLE job_signatures ADD COLUMN IF NOT EXISTS was_applied  BOOLEAN DEFAULT FALSE;
ALTER TABLE job_signatures ADD COLUMN IF NOT EXISTS was_rejected BOOLEAN DEFAULT FALSE;

UPDATE job_signatures js
SET was_applied  = COALESCE(uji.applied, FALSE),
    was_rejected = COALESCE(uji.rejected, FALSE)
FROM user_job_interactions uji
WHERE uji.job_id = js.original_job_id
  AND uji.user_id = js.user_id
  AND js.was_applied = FALSE
  AND js.was_rejected = FALSE;

-- Covers the new lookup: filter by user, match on company + title.
CREATE INDEX IF NOT EXISTS idx_job_signatures_user_lookup
    ON job_signatures(user_id, company, normalized_title);
